warn-on = [
  "clippy::all",
  "clippy::pedantic",
  "clippy::nursery",
]

allow = [
  "clippy::module_name_repetitions", # module tests often mirror file names
  "clippy::doc_markdown",            # allow bare Markdown links in docs
]
